pipeline {
    
    agent any
    
    triggers {
        pollSCM('* * * * *')
    }

    stages {
        stage('Preparation') {
            steps {
                echo 'Hello, pipeline1'
                checkout([$class: 'GitSCM', branches: [[name: "*/master"]], 
                userRemoteConfigs: [[credentialsId: "hule1", url: "https://github.com/huleTW/pipeline-exercise.git/"]]])

                sh """git submodule update --recursive --remote"""
            }
        }
       
        stage('Build') {
            steps {
                sh './gradlew clean build'
            }
        }
    }
}
